#
# imageserver/Makefile
#
# History:
#    2010/03/23 - [Jian Tang] created file
#
# Copyright (C) 2010, Ambarella, Inc.
#
# All rights reserved. No Part of this file may be reproduced, stored
# in a retrieval system, or transmitted, in any form, or by any means,
# electronic, mechanical, photocopying, recording, or otherwise,
# without the prior consent of Ambarella, Inc.
#

default: all

AMBABUILD_TOPDIR  = $(word 1, $(subst /app/ipcam, ,$(shell pwd)))
MODULE_NAME		:= NTPC

export AMBABUILD_TOPDIR

-include $(AMBABUILD_TOPDIR)/build/app/common.mk
-include $(AMBABUILD_TOPDIR)/.config
-include $(AMBABUILD_TOPDIR)/app/ipcam/mediaserver/config.mk

ifeq ($(BUILD_AMBARELLA_TEXTINSERT_PACKAGE), y)
LINK_TEXT_INSERT = -L$(PREBUILD_DIR)/third-party/freetype/lib \
			-L $(PREBUILD_DIR)/textinsert \
			-lfreetype -ltextinsert -lpthread
endif

LINK_FLAG = -L $(MW_LIB_DIR) \
			-L $(SYS_LIB_DIR) \
			-L $(PREBUILD_DIR)/imgproc \
			-L $(PREBUILD_DIR)/third-party/dbus/lib \
			$(SYS_LIB_LD) \
			$(MW_LIB_LD) \
			-limg_algo_a5s -ldbus-1


MODULE_INC = -I$(AMBABUILD_TOPDIR)/build/include \
			-I$(AMBABUILD_TOPDIR)/build/include/arch \
			-I$(AMBABUILD_TOPDIR) \
			-I$(AMBABUILD_TOPDIR)/mw/amp/include \
			-I$(AMBABUILD_TOPDIR)/packages/textinsert
MODULE_DEF =


CFLAG = $(MODULE_INC) -g -O0 -Wall

.PHONY: all clean

all:
	@echo "    compile NTPC..."
	@$(AMBA_MAKEFILE_V)$(CROSS_COMPILE)gcc $(CFLAG) -o NTPC ntp.c $(LINK_FLAG) $(LINK_TEXT_INSERT)
	$(AMBA_MAKEFILE_V)mkdir -p $(APP_PATH)
	$(AMBA_MAKEFILE_V)cp -a NTPC $(APP_PATH)
	$(AMBA_MAKEFILE_V)chmod +x $(APP_PATH)/NTPC

clean:
	$(AMBA_MAKEFILE_V)rm -f NTPC